# Exercice 1

Vous allez travailler sur le fichier « Iris.csv ».
1. Utilisez panda pour importer le fichier.

In [ ]:
import pandas as pd

chemin ="Iris.csv"

iris=pd.read_csv(chemin)

2. Pour chaque espèce, calculez le nombre d'individus.

In [ ]:
species={}

for i in iris["Species"]:
    if i not in species:
        species[i]=0
    species[i]+=1

print(species)

{'Iris-setosa': 50, 'Iris-versicolor': 50, 'Iris-virginica': 50}

3. Pour chaque espèce, calculez la moyenne de chaque paramètre : SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm.

In [ ]:
average={}

for index in range(len(iris["Id"])):
    if iris["Species"][index] not in average:
        average[iris["Species"][index]]={"SepalLengthCm":0, "SepalWidthCm":0, "PetalLengthCm":0, "PetalWidthCm":0}
    for element in average[iris["Species"][index]]:
        average[iris["Species"][index]][element]+=iris[element][index]/species[iris["Species"][index]]

print(average)

{'Iris-setosa': {'SepalLengthCm': 5.006, 'SepalWidthCm': 3.418, 'PetalLengthCm': 1.464000000000001, 'PetalWidthCm': 0.24400000000000016}, 'Iris-versicolor': {'SepalLengthCm': 5.936, 'SepalWidthCm': 2.77, 'PetalLengthCm': 4.26, 'PetalWidthCm': 1.3260000000000007}, 'Iris-virginica': {'SepalLengthCm': 6.588000000000002, 'SepalWidthCm': 2.9740000000000006, 'PetalLengthCm': 5.552000000000001, 'PetalWidthCm': 2.026000000000001}}

4. Affichez les lignes où les fleurs ont une longueur de sépale (SepalLengthCm) inférieure ou égale à 5.

In [ ]:
iris[iris["SepalLengthCm"]<=5]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
22,23,4.6,3.6,1.0,0.2,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
35,36,5.0,3.2,1.2,0.2,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
40,41,5.0,3.5,1.3,0.3,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
43,44,5.0,3.5,1.6,0.6,Iris-setosa
45,46,4.8,3.0,1.4,0.3,Iris-setosa
47,48,4.6,3.2,1.4,0.2,Iris-setosa
49,50,5.0,3.3,1.4,0.2,Iris-setosa
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor
106,107,4.9,2.5,4.5,1.7,Iris-virginica

5. Affichez les lignes où les fleurs ont une longueur de sépale inférieure ou égale à 5 cm et une longueur de pétale supérieure ou égale à 1,5 cm.

In [ ]:
a=iris[iris["SepalLengthCm"]<=5]
b=a[a["PetalLengthCm"]>=1.5]
b

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
3,4,4.6,3.1,1.5,0.2,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
43,44,5.0,3.5,1.6,0.6,Iris-setosa
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor
106,107,4.9,2.5,4.5,1.7,Iris-virginica

6. Afficher les lignes par ordre décroissant en fonction du paramètre PetalWidthCm.

In [ ]:
a = iris.sort_values("PetalWidthCm", ascending = False)
a

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
...,...,...,...,...,...,...
13,14,4.3,3.0,1.1,0.1,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa

# Exercice 2

Écrivez une fonction qui affiche la table de multiplication d'un nombre saisi par l'utilisateur. La
fonction doit générer une erreur si le nombre n'est pas compris entre 0 et 10. La fonction doit
également gérer le cas où l'utilisateur aurait saisi une chaîne de caractères et lui
demander de recommencer.

In [ ]:
def multiplicationTable():
    rep=False
    while rep==False:
        try:
            number=int(input("Quel table de multiplication voulez vous ? "))
        except ValueError:
            print("Cette valeur n'est pas un nombre.")
        else:
            rep=True
    if number<0 or number>10:
        raise Exception("La valeur doit être entre 0 et 10.")
    for i in range(0,11):
        print(i*number)

In [ ]:
multiplicationTable()

Which mutiplication table do you want ? 5
0
5
10
15
20
25
30
35
40
45
50

In [ ]:
multiplicationTable()

Which mutiplication table do you want ? 11

Exception: The value must be between O and 10.

In [ ]:
multiplicationTable()

Which mutiplication table do you want ? hello
This value is not a number.
Which mutiplication table do you want ? coucou
This value is not a number.
Which mutiplication table do you want ? bonjour
This value is not a number.
Which mutiplication table do you want ? 2
0
2
4
6
8
10
12
14
16
18
20

# Exercice 3

1. Écrivez une classe d'articles, pour laquelle vous pouvez spécifier un nom, un type d'article, un prix et une quantité.

In [1]:
class Item():
    def __init__(self,name,itemType,prix,quantite):
        self.name=name
        self.itemType=itemType
        self.prix=prix
        self.quantite=quantite
    def get_name(self):
        return self.name
    def get_itemType(self):
        return self.itemType
    def get_prix(self):
        return self.prix
    def get_quantite(self):
        return self.quantite
    def __str__(self):
        return self.name

2. Écrivez une classe « magasin » avec un nom et une liste d'articles à vendre. Cette classe doit pouvoir ajouter un article à sa liste de vente, vendre et réapprovisionner un article déjà présent dans sa liste. L'impression de cette classe affiche les types d'articles en vente dans le magasin et la quantité restante. Notez que si un article est épuisé, il ne peut plus être vendu.

In [5]:
class Magasin():
    def __init__(self,name):
        self.name=name
        self.itemsVendu=[]
    def get_name(self):
        return self.name
    def get_item_vendu(self):
        return self.itemsVendu
    def ajoutItem(self,item):
        if item not in self.itemsVendu:
            self.itemsVendu.append(item)
    def venteItem(self,item):
        if item.get_quantite()>0 and item in self.itemsVendu:
            item.quantite-=1
        else:
            print("Cet item n'est pas à vendre.")
    def rajoutItem(self,item,quantite):
        if item in self.itemsVendu:
            item.quantite+= quantite
    def __str__(self):
        return("Name %s \nItems vendu : %s"%(self.name,str([item.get_name() for item in self.itemsVendu])))
    def __len__(self):
        return len(self.itemsVendu)

In [6]:
item1=Item("Tomate","Fruit",2,2)

In [7]:
monMagasin=Magasin("Marina's Store")
monMagasin.ajoutItem(item1)
print(monMagasin)

Name Marina's Store
Items vendu : ['Tomate']

In [8]:
monMagasin.venteItem(item1)
item1.get_quantite()

1

In [9]:
monMagasin.rajoutItem(item1,10)

In [10]:
item1.get_quantite()

11

In [11]:
len(monMagasin)

1