# Exercice 1

You are going to work on the "Iris.csv" file.
1. Use panda to import the file.

In [2]:
import pandas as pd 

chemin ="Iris.csv"

iris=pd.read_csv(chemin)

2. For each species, calculate the number of individuals.

In [3]:
species={}

for i in iris["Species"]:
    if i not in species:
        species[i]=0
    species[i]+=1

print(species)

{'Iris-setosa': 50, 'Iris-versicolor': 50, 'Iris-virginica': 50}

3. For each species, calculate the average of each parameter: SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm.

In [4]:
average={}

for index in range(len(iris["Id"])):
    if iris["Species"][index] not in average:
        average[iris["Species"][index]]={"SepalLengthCm":0, "SepalWidthCm":0, "PetalLengthCm":0, "PetalWidthCm":0}
    for element in average[iris["Species"][index]]:
        average[iris["Species"][index]][element]+=iris[element][index]/species[iris["Species"][index]]

print(average)

{'Iris-setosa': {'SepalLengthCm': 5.006, 'SepalWidthCm': 3.418, 'PetalLengthCm': 1.464000000000001, 'PetalWidthCm': 0.24400000000000016}, 'Iris-versicolor': {'SepalLengthCm': 5.936, 'SepalWidthCm': 2.77, 'PetalLengthCm': 4.26, 'PetalWidthCm': 1.3260000000000007}, 'Iris-virginica': {'SepalLengthCm': 6.588000000000002, 'SepalWidthCm': 2.9740000000000006, 'PetalLengthCm': 5.552000000000001, 'PetalWidthCm': 2.026000000000001}}

4. Display lines where flowers have a SepalLengthCm less than or equal to 5.

In [5]:
iris[iris["SepalLengthCm"]<=5]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
22,23,4.6,3.6,1.0,0.2,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
35,36,5.0,3.2,1.2,0.2,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
40,41,5.0,3.5,1.3,0.3,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
43,44,5.0,3.5,1.6,0.6,Iris-setosa
45,46,4.8,3.0,1.4,0.3,Iris-setosa
47,48,4.6,3.2,1.4,0.2,Iris-setosa
49,50,5.0,3.3,1.4,0.2,Iris-setosa
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor
106,107,4.9,2.5,4.5,1.7,Iris-virginica

5. Display rows where flowers have SepalLengthCm less than or equal to 5 and PetalLengthCm greater than or equal to 1.5.

In [6]:
a=iris[iris["SepalLengthCm"]<=5]
b=a[a["PetalLengthCm"]>=1.5]
b

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
3,4,4.6,3.1,1.5,0.2,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
43,44,5.0,3.5,1.6,0.6,Iris-setosa
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor
106,107,4.9,2.5,4.5,1.7,Iris-virginica

6. Display lines in descending order according to the PetalWidthCm parameter.

In [7]:
a = iris.sort_values("PetalWidthCm", ascending = False)
a

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
...,...,...,...,...,...,...
13,14,4.3,3.0,1.1,0.1,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa

# Exercice 2

Write a function that displays the multiplication table for a number entered by the user. The
function should generate an error if the number is not between 0 and 10. The function must
also handle the possibility that the user may have entered a string of characters and be
asked to start again.

In [14]:
def multiplicationTable():
    rep=False
    while rep==False:
        try:
            number=int(input("Which mutiplication table do you want ? "))
        except ValueError:
            print("This value is not a number.")
        else:
            rep=True
    if number<0 or number>10:
        raise Exception("The value must be between O and 10.")
    for i in range(0,11):
        print(i*number)

In [11]:
multiplicationTable()

Which mutiplication table do you want ? 5
0
5
10
15
20
25
30
35
40
45
50

In [15]:
multiplicationTable()

Which mutiplication table do you want ? 11

Exception: The value must be between O and 10.

In [16]:
multiplicationTable()

Which mutiplication table do you want ? hello
This value is not a number.
Which mutiplication table do you want ? coucou
This value is not a number.
Which mutiplication table do you want ? bonjour
This value is not a number.
Which mutiplication table do you want ? 2
0
2
4
6
8
10
12
14
16
18
20

# Exercice 3

1. Write an item class, for which you can specify a name, item type, price and quantity.

In [19]:
class Item():
    def __init__(self,name,itemType,price,quantity):
        self.name=name
        self.itemType=itemType
        self.price=price
        self.quantity=quantity
    def get_name(self):
        return self.name
    def get_itemType(self):
        return self.itemType
    def get_price(self):
        return self.price
    def get_quantity(self):
        return self.quantity
    def __str__(self):
        return self.name

2. Write a store class with a name and a list of items for sale. This class must be able to add an item to its sales list, sell and replenish an item already in its list. The printout of this class shows the types of items on sale in the store and the quantity remaining. Note that if an item is sold out, it can no longer be sold.

In [36]:
class Store():
    def __init__(self,name):
        self.name=name
        self.itemsSold=[]
    def get_name(self):
        return self.name
    def get_item_sold(self):
        return self.itemsSold
    def addItem(self,item):
        if item not in self.itemsSold:
            self.itemsSold.append(item)
    def sellItem(self,item):
        if item.get_quantity()>0 and item in self.itemsSold:
            item.quantity-=1
        else:
            print("This item is not for sale.")
    def replenishItem(self,item,quantity):
        if item in self.itemsSold:
            item.quantity+= quantity
    def __str__(self):
        return("Name %s \nItems sold : %s"%(self.name,str([item.get_name() for item in self.itemsSold])))
    def __len__(self):
        return len(self.itemsSold)

In [39]:
item1=Item("Tomatoes","Fruit",2,2)

In [40]:
myStore=Store("Marina's Store")
myStore.addItem(item1)
print(myStore)

Name Marina's Store
Items sold : ['Tomatoes']

In [41]:
myStore.sellItem(item1)
item1.get_quantity()

1

In [42]:
myStore.replenishItem(item1,10)

In [43]:
item1.get_quantity()

11

In [44]:
len(myStore)

1